-- 既存のpostsテーブルのslugにユニーク制約があることを確認
ALTER TABLE posts ADD CONSTRAINT posts_slug_unique UNIQUE (slug);

-- アナリティクスデータ用のテーブル
CREATE TABLE analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT REFERENCES posts(slug) ON DELETE CASCADE,
  page_path TEXT NOT NULL,
  visitor_id TEXT,
  session_id TEXT,
  referrer TEXT,
  user_agent TEXT,
  device_type TEXT,
  country TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  search_query TEXT
);

-- Google Search Console用のデータテーブル
CREATE TABLE search_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT REFERENCES posts(slug) ON DELETE CASCADE,
  query TEXT,
  clicks INTEGER DEFAULT 0,
  impressions INTEGER DEFAULT 0,
  position FLOAT,
  date DATE,
  device TEXT,
  country TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(slug, date, query)
);

-- インデックスの作成
CREATE INDEX idx_analytics_slug ON analytics(slug);
CREATE INDEX idx_analytics_created_at ON analytics(created_at);
CREATE INDEX idx_search_analytics_slug ON search_analytics(slug);
CREATE INDEX idx_search_analytics_date ON search_analytics(date); 